"""Application configuration."""

APP_NAME = "ShopKit"
VERSION = "0.2.0"

# Pricing
CURRENCY = "EUR"
TAX_RATE = 0.19
FREE_SHIPPING_THRESHOLD = 100.0
SHIPPING_FLAT_FEE = 4.99

# Coupons: code -> percentage off
COUPON_CODES = {
    "WELCOME10": 0.10,
    "VIP20": 0.20,
}
LOYALTY_POINTS_PER_UNIT = 2

# Auth
SESSION_TTL_SECONDS = 7200
MIN_PASSWORD_LENGTH = 8
PASSWORD_HASH_ROUNDS = 12
